### ISSUE TITLE
Removes necessary spaces in calc function

### ISSUE THREAD

**Issue by gabeseltzer** [armin-pfaeffle/atom-minify#46]
I'm writing a website, and I have the following lines of css:
```css
.teams-and-prizes>div>div>.prize {
    width: calc(100% + 40px);
    border-bottom: 1px solid #e2e2e2;
}
```
When I minify my css (on a PC) the space gets removed from either side of the + sign:

```css
.teams-and-prizes>div>div>p{width:calc(100%+40px); (and so on...)
```

This causes the expression to break. My friend tried minifying it on his mac, and it works fine. We both have the same version of the package.
