### ISSUE TITLE
Minifying Calc() function with "+"

### ISSUE THREAD

**Issue by ciekals11** [armin-pfaeffle/atom-minify#68]
**Summary:**
minifying to minified file as well as direct minify makes function Calc() with "+" sign to minify wrongly
for example "Calc(50% + 80px)" is minified to "Calc(50%+80px)" which is not recognised as browsers.

**Steps to reproduce:**
1. create selector that uses "Calc" function and use "+" sign
2. minify file with "YUI Compressor"

**Expected result:**
Selector
```CSS
.foo {
    width: Calc(50% + 80px);
}
```
Should be minified into
```CSS
.foo{width:Calc(50% + 80px)}
```

**Actual result:**
```CSS
.foo{width:Calc(50%+80px)}
```
